### ISSUE TITLE
Log dir not remove with `--remove-all` and not proxy

### ISSUE THREAD

**Issue by horkko** [genouest/biomaj-daemon#2]
Hi,

I've noticed a new behavior with micro services architecture, in particular when I want to completely remove a bank using `--remove-all` option. In my case, I only use micro service architecture for download, I do not used a proxy at all.
So when I want to remove a bank, the bank log directory is not removed, because of [this](https://github.com/genouest/biomaj-daemon/blob/55a0ae86410f649721c6dac12d836510865fee30/biomaj_daemon/daemon/utils.py#L472) and then of [that](https://github.com/genouest/biomaj/blob/1bd2d1aed298a39c9ca247814a2685605e7ca89a/biomaj/bank.py#L928)
Is there a good reason for that?

Thanks

Emmanuel

**Comment by osallou** [comment]
In non proxy, all actions show current action log, not always in proxy
mode. Will modify non proxy case to deactivate logs in remove all action
